version: "3.8"

services:
  backend-app:
    restart: always
    build:
      context: .
    ports:
      - "8000:8000"
    depends_on:
      database:
        condition: service_healthy
    volumes:
      - ./src:/src
    environment:
      - DB_HOST=database
      - DB_PORT=5432
      - DB_NAME=rest_db
      - DB_USER=rest_user
      - DB_PASS=pass
    command: >
      sh -c "python manage.py runserver 0.0.0.0:8000"
  database:
    restart: always
    image: postgres:14.6-alpine
    environment:
      - POSTGRES_DB=rest_db
      - POSTGRES_USER=rest_user
      - POSTGRES_PASSWORD=pass
    volumes:
      - ./db_data:/var/lib/postgresql/data/
    healthcheck:
      test: ["CMD-SHELL", "sh -c 'pg_isready -U rest_user -d rest_db'" ]
      interval: 10s
      timeout: 5s
      retries: 5
